export interface trenchingProduct {
  "SL No.": number;
  "Category": string;
  "Base Code": string;
  "Suffix": string;
  "Parsed Size": string;
  "Height (in)": number | null;
  "Material & Type": string;
  "Description": string;
  "Weight (lbs)": number | null;
  "Trenching NO. (Raw)": string;
}

export const trenching_PRODUCTS: trenchingProduct[] = [
    {
        "SL No.": 1,
        "Category": "ROUND RISERS",
        "Base Code": "13001",
        "Suffix": "A",
        "Parsed Size": "22\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.00 EXTNS FOR 22\" - CAST IRON - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13001 A 22 X 1.00 CI"
    },
    {
        "SL No.": 2,
        "Category": "ROUND RISERS",
        "Base Code": "13001",
        "Suffix": "B",
        "Parsed Size": "22\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.50 EXTNS FOR 22\" - CAST IRON - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 35,
        "Trenching NO. (Raw)": "13001 B 22 X 1.50 CI"
    },
    {
        "SL No.": 3,
        "Category": "ROUND RISERS",
        "Base Code": "13001",
        "Suffix": "C",
        "Parsed Size": "22\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.00 EXTNS FOR 22\" - CAST IRON - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13001 C 22 X 2.00 CI"
    },
    {
        "SL No.": 4,
        "Category": "ROUND RISERS",
        "Base Code": "13001",
        "Suffix": "D",
        "Parsed Size": "22\"",
        "Height (in)": 2.5,
        "Material & Type": "Cast Iron",
        "Description": "2.50 EXTNS FOR 22\" - CAST IRON - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13001 D 22 X 2.50 CI"
    },
    {
        "SL No.": 5,
        "Category": "ROUND RISERS",
        "Base Code": "13001",
        "Suffix": "E",
        "Parsed Size": "22\"",
        "Height (in)": 3,
        "Material & Type": "Cast Iron",
        "Description": "3.00 EXTNS FOR 22\" - CAST IRON - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 70,
        "Trenching NO. (Raw)": "13001 E 22 X 3.00 CI"
    },
    {
        "SL No.": 6,
        "Category": "ROUND RISERS",
        "Base Code": "13001",
        "Suffix": "F",
        "Parsed Size": "22\"",
        "Height (in)": 4,
        "Material & Type": "Cast Iron",
        "Description": "4.00 EXTNS FOR 22\" - CAST IRON - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13001 F 22 X 4.00 CI"
    },
    {
        "SL No.": 7,
        "Category": "ROUND RISERS",
        "Base Code": "13002",
        "Suffix": "A",
        "Parsed Size": "22\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.00 EXTNS FOR 22\" - STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13002 A 22 X 1.00 ADJ"
    },
    {
        "SL No.": 8,
        "Category": "ROUND RISERS",
        "Base Code": "13002",
        "Suffix": "B",
        "Parsed Size": "22\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.50 EXTNS FOR 22\" -STEEL ADJUSTABLE- FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 35,
        "Trenching NO. (Raw)": "13002 B 22 X 1.50 ADJ"
    },
    {
        "SL No.": 9,
        "Category": "ROUND RISERS",
        "Base Code": "13002",
        "Suffix": "C",
        "Parsed Size": "22\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2.00 EXTNS FOR 22\" - STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13002 C 22 X 2.00 ADJ"
    },
    {
        "SL No.": 10,
        "Category": "ROUND RISERS",
        "Base Code": "13002",
        "Suffix": "D",
        "Parsed Size": "22\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Adjustable",
        "Description": "2.50 EXTNS FOR 22\" - STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13002 D 22 X 2.50 ADJ"
    },
    {
        "SL No.": 11,
        "Category": "ROUND RISERS",
        "Base Code": "13002",
        "Suffix": "E",
        "Parsed Size": "22\"",
        "Height (in)": 3,
        "Material & Type": "Steel Adjustable",
        "Description": "3.00 EXTNS FOR 22\" - STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 70,
        "Trenching NO. (Raw)": "13002 E 22 X 3.00 ADJ"
    },
    {
        "SL No.": 12,
        "Category": "ROUND RISERS",
        "Base Code": "13002",
        "Suffix": "F",
        "Parsed Size": "22\"",
        "Height (in)": 4,
        "Material & Type": "Steel Adjustable",
        "Description": "4.00 EXTNS FOR 22\" - STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13002 F 22 X 4.00 ADJ"
    },
    {
        "SL No.": 13,
        "Category": "ROUND RISERS",
        "Base Code": "13003",
        "Suffix": "A",
        "Parsed Size": "22\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.00 EXTNS FOR 22\" - STEEL FIXED - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13003 A 22 X 1.00 FIX"
    },
    {
        "SL No.": 14,
        "Category": "ROUND RISERS",
        "Base Code": "13003",
        "Suffix": "B",
        "Parsed Size": "22\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.50 EXTNS FOR 22\" - STEEL FIXED - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 35,
        "Trenching NO. (Raw)": "13003 B 22 X 1.50 FIX"
    },
    {
        "SL No.": 15,
        "Category": "ROUND RISERS",
        "Base Code": "13003",
        "Suffix": "C",
        "Parsed Size": "22\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2.00 EXTNS FOR 22\" - STEEL FIXED - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13003 C 22 X 2.00 FIX"
    },
    {
        "SL No.": 16,
        "Category": "ROUND RISERS",
        "Base Code": "13003",
        "Suffix": "D",
        "Parsed Size": "22\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.50 EXTNS FOR 22\" - STEEL FIXED - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13003 D 22 X 2.50 FIX"
    },
    {
        "SL No.": 17,
        "Category": "ROUND RISERS",
        "Base Code": "13003",
        "Suffix": "E",
        "Parsed Size": "22\"",
        "Height (in)": 3,
        "Material & Type": "Steel Fixed",
        "Description": "3.00 EXTNS FOR 22\" - STEEL FIXED - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": 70,
        "Trenching NO. (Raw)": "13003 E 22 X 3.00 FIX"
    },
    {
        "SL No.": 18,
        "Category": "ROUND RISERS",
        "Base Code": "13003",
        "Suffix": "F",
        "Parsed Size": "22\"",
        "Height (in)": 4,
        "Material & Type": "Steel Fixed",
        "Description": "4.00 EXTNS FOR 22\" - STEEL FIXED - FOR 1.50 THICKNESS COVER (EJ 1490)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13003 F 22 X 4.00 FIX"
    },
    {
        "SL No.": 19,
        "Category": "ROUND RISERS",
        "Base Code": "13101",
        "Suffix": "A",
        "Parsed Size": "22.75\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 EXTNS FOR 22.75\" - CAST IRON - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13101 A 22.75 X 1.00 CI"
    },
    {
        "SL No.": 20,
        "Category": "ROUND RISERS",
        "Base Code": "13101",
        "Suffix": "B",
        "Parsed Size": "22.75\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTNS FOR 22.75\" - CAST IRON - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13101 B 22.75 X 1.50 CI"
    },
    {
        "SL No.": 21,
        "Category": "ROUND RISERS",
        "Base Code": "13101",
        "Suffix": "C",
        "Parsed Size": "22.75\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.0 EXTNS FOR 22.75\" - CAST IRON - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13101 C 22.75 X 2.00 CI"
    },
    {
        "SL No.": 22,
        "Category": "ROUND RISERS",
        "Base Code": "13101",
        "Suffix": "D",
        "Parsed Size": "22.75\"",
        "Height (in)": 2.5,
        "Material & Type": "Cast Iron",
        "Description": "2.5 EXTNS FOR 22.75\" - CAST IRON - FOR 1.75 THICKNESS COVER(N 1772)",
        "Weight (lbs)": 70,
        "Trenching NO. (Raw)": "13101 D 22.75 X 2.50 CI"
    },
    {
        "SL No.": 23,
        "Category": "ROUND RISERS",
        "Base Code": "13101",
        "Suffix": "E",
        "Parsed Size": "22.75\"",
        "Height (in)": 3,
        "Material & Type": "Cast Iron",
        "Description": "3.0 EXTNS FOR 22.75\" - CAST IRON - FOR 1.75 THICKNESS COVER(N 1772)",
        "Weight (lbs)": 80,
        "Trenching NO. (Raw)": "13101 E 22.75 X 3.00 CI"
    },
    {
        "SL No.": 24,
        "Category": "ROUND RISERS",
        "Base Code": "13101",
        "Suffix": "F",
        "Parsed Size": "22.75\"",
        "Height (in)": 4,
        "Material & Type": "Cast Iron",
        "Description": "4.0 EXTNS FOR 22.75\" - CAST IRON - FOR 1.75 THICKNESS COVER(N 1772)",
        "Weight (lbs)": 100,
        "Trenching NO. (Raw)": "13101 F 22.75 X 4.00 CI"
    },
    {
        "SL No.": 25,
        "Category": "ROUND RISERS",
        "Base Code": "13102",
        "Suffix": "A",
        "Parsed Size": "22.75\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 22.75\" STEEL ADJUSTABLE - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13102 A 22.75 X 1.00 ADJ"
    },
    {
        "SL No.": 26,
        "Category": "ROUND RISERS",
        "Base Code": "13102",
        "Suffix": "B",
        "Parsed Size": "22.75\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 22.75\" STEEL ADJUSTABLE - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13102 B 22.75 X 1.50 ADJ"
    },
    {
        "SL No.": 27,
        "Category": "ROUND RISERS",
        "Base Code": "13102",
        "Suffix": "C",
        "Parsed Size": "22.75\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 22.75\" STEEL ADJUSTABLE - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13102 C 22.75 X 2.00 ADJ"
    },
    {
        "SL No.": 28,
        "Category": "ROUND RISERS",
        "Base Code": "13102",
        "Suffix": "D",
        "Parsed Size": "22.75\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Adjustable",
        "Description": "2.5 X 22.75\" STEEL ADJUSTABLE - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 70,
        "Trenching NO. (Raw)": "13102 D 22.75 X 2.50 ADJ"
    },
    {
        "SL No.": 29,
        "Category": "ROUND RISERS",
        "Base Code": "13102",
        "Suffix": "E",
        "Parsed Size": "22.75\"",
        "Height (in)": 3,
        "Material & Type": "Steel Adjustable",
        "Description": "3.0 X 22.75\" STEEL ADJUSTABLE - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 80,
        "Trenching NO. (Raw)": "13102 E 22.75 X 3.00 ADJ"
    },
    {
        "SL No.": 30,
        "Category": "ROUND RISERS",
        "Base Code": "13102",
        "Suffix": "F",
        "Parsed Size": "22.75\"",
        "Height (in)": 4,
        "Material & Type": "Steel Adjustable",
        "Description": "4.0 X 22.75\" STEEL ADJUSTABLE - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 100,
        "Trenching NO. (Raw)": "13102 F 22.75 X 4.00 ADJ"
    },
    {
        "SL No.": 31,
        "Category": "ROUND RISERS",
        "Base Code": "13103",
        "Suffix": "A",
        "Parsed Size": "22.75\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 22.75\" STEEL FIXED- FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13103 A 22.75 X 1.00 FIX"
    },
    {
        "SL No.": 32,
        "Category": "ROUND RISERS",
        "Base Code": "13103",
        "Suffix": "B",
        "Parsed Size": "22.75\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 22.75\" STEEL FIXED - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13103 B 22.75 X 1.50 FIX"
    },
    {
        "SL No.": 33,
        "Category": "ROUND RISERS",
        "Base Code": "13103",
        "Suffix": "C",
        "Parsed Size": "22.75\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 22.75\" STEEL FIXED - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13103 C 22.75 X 2.00 FIX"
    },
    {
        "SL No.": 34,
        "Category": "ROUND RISERS",
        "Base Code": "13103",
        "Suffix": "D",
        "Parsed Size": "22.75\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.5 X 22.75\" STEEL FIXED - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 70,
        "Trenching NO. (Raw)": "13103 D 22.75 X 2.50 FIX"
    },
    {
        "SL No.": 35,
        "Category": "ROUND RISERS",
        "Base Code": "13103",
        "Suffix": "E",
        "Parsed Size": "22.75\"",
        "Height (in)": 3,
        "Material & Type": "Steel Fixed",
        "Description": "3.0 X 22.75\" STEEL FIXED - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 80,
        "Trenching NO. (Raw)": "13103 E 22.75 X 3.00 FIX"
    },
    {
        "SL No.": 36,
        "Category": "ROUND RISERS",
        "Base Code": "13103",
        "Suffix": "F",
        "Parsed Size": "22.75\"",
        "Height (in)": 4,
        "Material & Type": "Steel Fixed",
        "Description": "4.0 X 22.75\" STEEL FIXED - FOR 1.75 THICKNESS COVER (N 1772)",
        "Weight (lbs)": 100,
        "Trenching NO. (Raw)": "13103 F 22.75 X 4.00 FIX"
    },
    {
        "SL No.": 37,
        "Category": "ROUND RISERS",
        "Base Code": "13201",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.00 EXTNS FOR 24\" - CAST IRON - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13201 A 24 X 1.00 CI"
    },
    {
        "SL No.": 38,
        "Category": "ROUND RISERS",
        "Base Code": "13201",
        "Suffix": "B",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.50 EXTNS FOR 24\" - CAST IRON - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": 28,
        "Trenching NO. (Raw)": "13201 B 24 X 1.50 CI"
    },
    {
        "SL No.": 39,
        "Category": "ROUND RISERS",
        "Base Code": "13201",
        "Suffix": "C",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.00 EXTNS FOR 24\" - CAST IRON - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": 34,
        "Trenching NO. (Raw)": "13201 C 24 X 2.00 CI"
    },
    {
        "SL No.": 40,
        "Category": "ROUND RISERS",
        "Base Code": "13202",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.00 X 24\" STEEL ADJUSTABLE - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13202 A 24 X 1.00 ADJ"
    },
    {
        "SL No.": 41,
        "Category": "ROUND RISERS",
        "Base Code": "13202",
        "Suffix": "B",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.50 X 24\" STEEL ADJUSTABLE - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": 28,
        "Trenching NO. (Raw)": "13202 B 24 X 1.50 ADJ"
    },
    {
        "SL No.": 42,
        "Category": "ROUND RISERS",
        "Base Code": "13202",
        "Suffix": "C",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2.00 X 24\" STEEL ADJUSTABLE - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": 34,
        "Trenching NO. (Raw)": "13202 C 24 X 2.00 ADJ"
    },
    {
        "SL No.": 43,
        "Category": "ROUND RISERS",
        "Base Code": "13203",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.00 X 24\" STEEL FIXED - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13203 A 24 X 1.00 FIX"
    },
    {
        "SL No.": 44,
        "Category": "ROUND RISERS",
        "Base Code": "13203",
        "Suffix": "B",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.50 X 24\" STEEL FIXED - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": 28,
        "Trenching NO. (Raw)": "13203 B 24 X 1.50 FIX"
    },
    {
        "SL No.": 45,
        "Category": "ROUND RISERS",
        "Base Code": "13203",
        "Suffix": "C",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2.00 X 24\" STEEL FIXED - FOR 1.25 THICKNESS COVER",
        "Weight (lbs)": 34,
        "Trenching NO. (Raw)": "13203 C 24 X 2.00 FIX"
    },
    {
        "SL No.": 46,
        "Category": "ROUND RISERS",
        "Base Code": "13206",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.00 X 24 CAST IRON - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13206 A 24 X 1.00 CI"
    },
    {
        "SL No.": 47,
        "Category": "ROUND RISERS",
        "Base Code": "13206",
        "Suffix": "B",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.50 X 24 CAST IRON - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13206 B 24 X 1.50 CI"
    },
    {
        "SL No.": 48,
        "Category": "ROUND RISERS",
        "Base Code": "13206",
        "Suffix": "C",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.00 X 24 CAST IRON - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13206 C 24 X 2.00 CI"
    },
    {
        "SL No.": 49,
        "Category": "ROUND RISERS",
        "Base Code": "13207",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.00 X 24 STEEL ADJUSTABLE - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13207 A 24 X 1.00 ADJ"
    },
    {
        "SL No.": 50,
        "Category": "ROUND RISERS",
        "Base Code": "13207",
        "Suffix": "B",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.50 X 24 STEEL ADJUSTABLE - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13207 B 24 X 1.50 ADJ"
    },
    {
        "SL No.": 51,
        "Category": "ROUND RISERS",
        "Base Code": "13207",
        "Suffix": "C",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2.00 X 24 STEEL ADJUSTABLE - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13207 C 24 X 2.00 ADJ"
    },
    {
        "SL No.": 52,
        "Category": "ROUND RISERS",
        "Base Code": "13208",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.00 X 24\" STEEL FIXED - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13208 A 24 X 1.00 FIX"
    },
    {
        "SL No.": 53,
        "Category": "ROUND RISERS",
        "Base Code": "13208",
        "Suffix": "B",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.50 X 24\" STEEL FIXED - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13208 B 24 X 1.50 FIX"
    },
    {
        "SL No.": 54,
        "Category": "ROUND RISERS",
        "Base Code": "13208",
        "Suffix": "C",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2.00 X 24\" STEEL FIXED - FOR 1 3/8 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13208 C 24 X 2.00 FIX"
    },
    {
        "SL No.": 55,
        "Category": "ROUND RISERS",
        "Base Code": "13209",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.00 X 24 CAST IRON - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13209 A 24X1.00 CI"
    },
    {
        "SL No.": 56,
        "Category": "ROUND RISERS",
        "Base Code": "13209",
        "Suffix": "B",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.50 X 24 CAST IRON - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13209 B 24X1.50 CI"
    },
    {
        "SL No.": 57,
        "Category": "ROUND RISERS",
        "Base Code": "13209",
        "Suffix": "C",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.00 X 24 CAST IRON - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13209 C 24X2.00 CI"
    },
    {
        "SL No.": 58,
        "Category": "ROUND RISERS",
        "Base Code": "13210",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.00 X 24 STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13210 A 24X1.00 ADJ"
    },
    {
        "SL No.": 59,
        "Category": "ROUND RISERS",
        "Base Code": "13210",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.50 X 24 STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13210 A 24X1.50 ADJ"
    },
    {
        "SL No.": 60,
        "Category": "ROUND RISERS",
        "Base Code": "13210",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2.00 X 24 STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13210 A 24X2.00 ADJ"
    },
    {
        "SL No.": 61,
        "Category": "ROUND RISERS",
        "Base Code": "13211",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.00 X 24 STEEL FIXED - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13211 A 24X1.00 FIX"
    },
    {
        "SL No.": 62,
        "Category": "ROUND RISERS",
        "Base Code": "13211",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.50 X 24 STEEL FIXED - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13211 A 24X1.50 FIX"
    },
    {
        "SL No.": 63,
        "Category": "ROUND RISERS",
        "Base Code": "13211",
        "Suffix": "A",
        "Parsed Size": "24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2.00 X 24 STEEL FIXED - FOR 1.50 THICKNESS COVER",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13211 A 24X2.00 FIX"
    },
    {
        "SL No.": 64,
        "Category": "ROUND RISERS",
        "Base Code": "13301",
        "Suffix": "A",
        "Parsed Size": "25.75\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 X 25.75 CAST IRON- FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13301 A 25.75X1.00 CI"
    },
    {
        "SL No.": 65,
        "Category": "ROUND RISERS",
        "Base Code": "13301",
        "Suffix": "B",
        "Parsed Size": "25.75\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 X 25.75 CAST IRON - FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13301 B 25.75X1.50 CI"
    },
    {
        "SL No.": 66,
        "Category": "ROUND RISERS",
        "Base Code": "13301",
        "Suffix": "C",
        "Parsed Size": "25.75\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2 X 25.75 CAST IRON - FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13301 C 25.75X2.00 CI"
    },
    {
        "SL No.": 67,
        "Category": "ROUND RISERS",
        "Base Code": "13302",
        "Suffix": "A",
        "Parsed Size": "25.75\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 25.75 STEEL ADJUSTABLE- FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13302 A 25.75X1.00 ADJ"
    },
    {
        "SL No.": 68,
        "Category": "ROUND RISERS",
        "Base Code": "13302",
        "Suffix": "B",
        "Parsed Size": "25.75\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 25.75 STEEL ADJUSTABLE - FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13302 B 25.75X1.50 ADJ"
    },
    {
        "SL No.": 69,
        "Category": "ROUND RISERS",
        "Base Code": "13302",
        "Suffix": "C",
        "Parsed Size": "25.75\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 25.75 STEEL ADJUSTABLE - FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13302 C 25.75X2.00 ADJ"
    },
    {
        "SL No.": 70,
        "Category": "ROUND RISERS",
        "Base Code": "13303",
        "Suffix": "A",
        "Parsed Size": "25.75\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 25.75 FIXED RISER - STEEL- FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13303 A 25.75X1.00 FIX"
    },
    {
        "SL No.": 71,
        "Category": "ROUND RISERS",
        "Base Code": "13303",
        "Suffix": "B",
        "Parsed Size": "25.75\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 25.75 FIXED RISER - STEEL - FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13303 B 25.75X1.50 FIX"
    },
    {
        "SL No.": 72,
        "Category": "ROUND RISERS",
        "Base Code": "13303",
        "Suffix": "C",
        "Parsed Size": "25.75\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 25.75 FIXED RISER - STEEL - FOR 1 3/8 THICKNESS COVER (1203)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13303 C 25.75X2.00 FIX"
    },
    {
        "SL No.": 73,
        "Category": "ROUND RISERS",
        "Base Code": "13401",
        "Suffix": "A",
        "Parsed Size": "26\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 EXTNS FOR 26\" - CAST IRON - FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13401 A 26X1.00 CI"
    },
    {
        "SL No.": 74,
        "Category": "ROUND RISERS",
        "Base Code": "13401",
        "Suffix": "B",
        "Parsed Size": "26\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTNS FOR 26\" - CAST IRON - FOR 1 1/8 THICKNESS COVER(MASS)",
        "Weight (lbs)": 40,
        "Trenching NO. (Raw)": "13401 B 26X1.50 CI"
    },
    {
        "SL No.": 75,
        "Category": "ROUND RISERS",
        "Base Code": "13401",
        "Suffix": "C",
        "Parsed Size": "26\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.0 EXTNS FOR 26\" - CAST IRON - FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13401 C 26X2.00 CI"
    },
    {
        "SL No.": 76,
        "Category": "ROUND RISERS",
        "Base Code": "13402",
        "Suffix": "A",
        "Parsed Size": "26\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 26 ADJUSTABLE RISER - STEEL- FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13402 A 26X1.00 ADJ"
    },
    {
        "SL No.": 77,
        "Category": "ROUND RISERS",
        "Base Code": "13402",
        "Suffix": "B",
        "Parsed Size": "26\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 26 ADJUSTABLE RISER - STEEL - FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": 40,
        "Trenching NO. (Raw)": "13402 B 26X1.50 ADJ"
    },
    {
        "SL No.": 78,
        "Category": "ROUND RISERS",
        "Base Code": "13402",
        "Suffix": "C",
        "Parsed Size": "26\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 26 ADJUSTABLE RISER - STEEL - FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13402 C 26X2.00 ADJ"
    },
    {
        "SL No.": 79,
        "Category": "ROUND RISERS",
        "Base Code": "13403",
        "Suffix": "A",
        "Parsed Size": "26\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 26 FIXED RISER - STEEL- FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13403 A 26X1.00 FIX"
    },
    {
        "SL No.": 80,
        "Category": "ROUND RISERS",
        "Base Code": "13403",
        "Suffix": "B",
        "Parsed Size": "26\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 26 FIXED RISER - STEEL - FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": 40,
        "Trenching NO. (Raw)": "13403 B 26X1.50 FIX"
    },
    {
        "SL No.": 81,
        "Category": "ROUND RISERS",
        "Base Code": "13403",
        "Suffix": "C",
        "Parsed Size": "26\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 26 FIXED RISER - STEEL - FOR 1 1/8 THICKNESS COVER (MASS)",
        "Weight (lbs)": 50,
        "Trenching NO. (Raw)": "13403 C 26X2.00 FIX"
    },
    {
        "SL No.": 82,
        "Category": "ROUND RISERS",
        "Base Code": "13410",
        "Suffix": "A",
        "Parsed Size": "26\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 26 FIXED RISER - STEEL- FOR 1.50 THICKNESS COVER (EJ 1045)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13410 A 26X1.00 FIX"
    },
    {
        "SL No.": 83,
        "Category": "ROUND RISERS",
        "Base Code": "13410",
        "Suffix": "B",
        "Parsed Size": "26\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 26 FIXED RISER - STEEL - FOR 1.50 THICKNESS COVER (EJ 1045)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13410 B 26X1.50 FIX"
    },
    {
        "SL No.": 84,
        "Category": "ROUND RISERS",
        "Base Code": "13410",
        "Suffix": "C",
        "Parsed Size": "26\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 26 FIXED RISER - STEEL - FOR 1.50 THICKNESS COVER (EJ 1045)",
        "Weight (lbs)": 60,
        "Trenching NO. (Raw)": "13410 C 26X2.00 FIX"
    },
    {
        "SL No.": 85,
        "Category": "ROUND RISERS",
        "Base Code": "13410",
        "Suffix": "D",
        "Parsed Size": "26\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.50 X 26 FIXED RISER - STEEL - FOR 1.50 THICKNESS COVER (EJ 1045)",
        "Weight (lbs)": 70,
        "Trenching NO. (Raw)": "13410 D 26X2.50 FIX"
    },
    {
        "SL No.": 86,
        "Category": "ROUND RISERS",
        "Base Code": "13410",
        "Suffix": "E",
        "Parsed Size": "26\"",
        "Height (in)": 3,
        "Material & Type": "Steel Fixed",
        "Description": "3.00 X 26 FIXED RISER - STEEL - FOR 1.50 THICKNESS COVER (EJ 1045)",
        "Weight (lbs)": 80,
        "Trenching NO. (Raw)": "13410 E 26X3.00 FIX"
    },
    {
        "SL No.": 87,
        "Category": "ROUND RISERS",
        "Base Code": "13410",
        "Suffix": "F",
        "Parsed Size": "26\"",
        "Height (in)": 4,
        "Material & Type": "Steel Fixed",
        "Description": "4.00 X 26 FIXED RISER - STEEL - FOR 1.50 THICKNESS COVER (EJ 1045)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13410 F 26X4.00 FIX"
    },
    {
        "SL No.": 88,
        "Category": "ROUND RISERS",
        "Base Code": "13501",
        "Suffix": "A",
        "Parsed Size": "26\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 26 FIXED RISER - STEEL - FOR 1.0 THICKNESS COVER (1202)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13501 A 26X1.00 FIX"
    },
    {
        "SL No.": 89,
        "Category": "ROUND RISERS",
        "Base Code": "13501",
        "Suffix": "B",
        "Parsed Size": "26\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 26 FIXED RISER - STEEL - FOR 1.5 THICKNESS COVER (1202)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13501 B 26X1.50 FIX"
    },
    {
        "SL No.": 90,
        "Category": "ROUND RISERS",
        "Base Code": "13501",
        "Suffix": "C",
        "Parsed Size": "26\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 26 FIXED RISER - STEEL - FOR 2.0 THICKNESS COVER (1202)",
        "Weight (lbs)": 65,
        "Trenching NO. (Raw)": "13501 C 26X2.00 FIX"
    },
    {
        "SL No.": 91,
        "Category": "ROUND RISERS",
        "Base Code": "13501",
        "Suffix": "A",
        "Parsed Size": "26\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "2 X 26 FIXED RISER - CAST IRON - FOR 1.0 THICKNESS COVER (1202)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13501 A 26X1.00 CI"
    },
    {
        "SL No.": 92,
        "Category": "ROUND RISERS",
        "Base Code": "13501",
        "Suffix": "B",
        "Parsed Size": "26\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "2 X 26 FIXED RISER - CAST IRON - FOR 1.5 THICKNESS COVER (1202)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13501 B 26X1.50 CI"
    },
    {
        "SL No.": 93,
        "Category": "ROUND RISERS",
        "Base Code": "13501",
        "Suffix": "C",
        "Parsed Size": "26\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2 X 26 FIXED RISER - CAST IRON - FOR 2.0 THICKNESS COVER (1202)",
        "Weight (lbs)": 65,
        "Trenching NO. (Raw)": "13501 C 26X2.00 CI"
    },
    {
        "SL No.": 94,
        "Category": "ROUND RISERS",
        "Base Code": "13601",
        "Suffix": "A",
        "Parsed Size": "32\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 EXTNS FOR 32\" - CAST IRON - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13601 A 32X1.00 CI"
    },
    {
        "SL No.": 95,
        "Category": "ROUND RISERS",
        "Base Code": "13601",
        "Suffix": "B",
        "Parsed Size": "32\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTNS FOR 32\" - CAST IRON - FOR 1.50 THICKNESS COVER(NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13601 B 32X1.50 CI"
    },
    {
        "SL No.": 96,
        "Category": "ROUND RISERS",
        "Base Code": "13601",
        "Suffix": "C",
        "Parsed Size": "32\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.0 EXTNS FOR 32\" - CAST IRON - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13601 C 32X2.00 CI"
    },
    {
        "SL No.": 97,
        "Category": "ROUND RISERS",
        "Base Code": "13602",
        "Suffix": "A",
        "Parsed Size": "32\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 32 STEEL ADJUSTABLE- FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13602 A 32X1.00 ADJ"
    },
    {
        "SL No.": 98,
        "Category": "ROUND RISERS",
        "Base Code": "13602",
        "Suffix": "B",
        "Parsed Size": "32\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 32 STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13602 B 32X1.50 ADJ"
    },
    {
        "SL No.": 99,
        "Category": "ROUND RISERS",
        "Base Code": "13602",
        "Suffix": "C",
        "Parsed Size": "32\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 32 STEEL ADJUSTABLE - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13602 C 32X2.00 ADJ"
    },
    {
        "SL No.": 100,
        "Category": "ROUND RISERS",
        "Base Code": "13603",
        "Suffix": "A",
        "Parsed Size": "32\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 32 STEEL FIXED- FOR 1.50 THICKNESS COVER(NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13603 A 32X1.00 FIX"
    },
    {
        "SL No.": 101,
        "Category": "ROUND RISERS",
        "Base Code": "13603",
        "Suffix": "B",
        "Parsed Size": "32\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 32 STEEL FIXED - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13603 B 32X1.50 FIX"
    },
    {
        "SL No.": 102,
        "Category": "ROUND RISERS",
        "Base Code": "13603",
        "Suffix": "C",
        "Parsed Size": "32\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 32 STEEL FIXED - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13603 C 32X2.00 FIX"
    },
    {
        "SL No.": 103,
        "Category": "ROUND RISERS",
        "Base Code": "13604",
        "Suffix": "A",
        "Parsed Size": "32\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 EXTNS FOR 32\" - CAST IRON - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13604 A 32X1.00 CI"
    },
    {
        "SL No.": 104,
        "Category": "ROUND RISERS",
        "Base Code": "13604",
        "Suffix": "B",
        "Parsed Size": "32\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTNS FOR 32\" - CAST IRON - FOR 1.75 THICKNESS COVER(NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13604 B 32X1.50 CI"
    },
    {
        "SL No.": 105,
        "Category": "ROUND RISERS",
        "Base Code": "13604",
        "Suffix": "C",
        "Parsed Size": "32\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.0 EXTNS FOR 32\" - CAST IRON - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13604 C 32X2.00 CI"
    },
    {
        "SL No.": 106,
        "Category": "ROUND RISERS",
        "Base Code": "13605",
        "Suffix": "A",
        "Parsed Size": "32\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 32 ADJUSTABLE RISER - STEEL- FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13605 A 32X1.00 ADJ"
    },
    {
        "SL No.": 107,
        "Category": "ROUND RISERS",
        "Base Code": "13605",
        "Suffix": "B",
        "Parsed Size": "32\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 32 ADJUSTABLE RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13605 B 32X1.50 ADJ"
    },
    {
        "SL No.": 108,
        "Category": "ROUND RISERS",
        "Base Code": "13605",
        "Suffix": "C",
        "Parsed Size": "32\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 32 ADJUSTABLE RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13605 C 32X2.00 ADJ"
    },
    {
        "SL No.": 109,
        "Category": "ROUND RISERS",
        "Base Code": "13606",
        "Suffix": "A",
        "Parsed Size": "32\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 32 FIXED RISER - STEEL- FOR 1.75 THICKNESS COVER(NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13606 A 32X1.00 FIX"
    },
    {
        "SL No.": 110,
        "Category": "ROUND RISERS",
        "Base Code": "13606",
        "Suffix": "B",
        "Parsed Size": "32\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 32 FIXED RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13606 B 32X1.50 FIX"
    },
    {
        "SL No.": 111,
        "Category": "ROUND RISERS",
        "Base Code": "13606",
        "Suffix": "C",
        "Parsed Size": "32\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 32 FIXED RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13606 C 32X2.00 FIX"
    },
    {
        "SL No.": 112,
        "Category": "ROUND RISERS",
        "Base Code": "13801",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 EXTNS FOR 36\" - CAST IRON - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13801 A 36X1.00 CI"
    },
    {
        "SL No.": 113,
        "Category": "ROUND RISERS",
        "Base Code": "13801",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTNS FOR 36\" - CAST IRON - FOR 1.50 THICKNESS COVER(NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13801 B 36X1.50 CI"
    },
    {
        "SL No.": 114,
        "Category": "ROUND RISERS",
        "Base Code": "13801",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.0 EXTNS FOR 36\" - CAST IRON - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13801 C 36X2.00 CI"
    },
    {
        "SL No.": 115,
        "Category": "ROUND RISERS",
        "Base Code": "13802",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 36 ADJUSTABLE RISER - STEEL- FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13802 A 36X1.00 ADJ"
    },
    {
        "SL No.": 116,
        "Category": "ROUND RISERS",
        "Base Code": "13802",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 36 ADJUSTABLE RISER - STEEL - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13802 B 36X1.50 ADJ"
    },
    {
        "SL No.": 117,
        "Category": "ROUND RISERS",
        "Base Code": "13802",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 36 ADJUSTABLE RISER - STEEL - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13802 C 36X2.00 ADJ"
    },
    {
        "SL No.": 118,
        "Category": "ROUND RISERS",
        "Base Code": "13803",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 36 FIXED RISER - STEEL- FOR 1.50 THICKNESS COVER(NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13803 A 36X1.00 FIX"
    },
    {
        "SL No.": 119,
        "Category": "ROUND RISERS",
        "Base Code": "13803",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 36 FIXED RISER - STEEL - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13803 B 36X1.50 FIX"
    },
    {
        "SL No.": 120,
        "Category": "ROUND RISERS",
        "Base Code": "13803",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 36 FIXED RISER - STEEL - FOR 1.50 THICKNESS COVER (NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13803 C 36X2.00 FIX"
    },
    {
        "SL No.": 121,
        "Category": "ROUND RISERS",
        "Base Code": "13804",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 EXTNS FOR 36\" - CAST IRON - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13804 A 36X1.00 CI"
    },
    {
        "SL No.": 122,
        "Category": "ROUND RISERS",
        "Base Code": "13804",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTNS FOR 36\" - CAST IRON - FOR 1.75 THICKNESS COVER(NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13804 B 36X1.50 CI"
    },
    {
        "SL No.": 123,
        "Category": "ROUND RISERS",
        "Base Code": "13804",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.0 EXTNS FOR 36\" - CAST IRON - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13804 C 36X2.00 CI"
    },
    {
        "SL No.": 124,
        "Category": "ROUND RISERS",
        "Base Code": "13805",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 36 ADJUSTABLE RISER - STEEL- FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13805 A 36X1.00 ADJ"
    },
    {
        "SL No.": 125,
        "Category": "ROUND RISERS",
        "Base Code": "13805",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 36 ADJUSTABLE RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13805 B 36X1.50 ADJ"
    },
    {
        "SL No.": 126,
        "Category": "ROUND RISERS",
        "Base Code": "13805",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 36 ADJUSTABLE RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13805 C 36X2.00 ADJ"
    },
    {
        "SL No.": 127,
        "Category": "ROUND RISERS",
        "Base Code": "13806",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 36 FIXED RISER - STEEL- FOR 1.75 THICKNESS COVER(NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13806 A 36X1.00 FIX"
    },
    {
        "SL No.": 128,
        "Category": "ROUND RISERS",
        "Base Code": "13806",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 36 FIXED RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13806 B 36X1.50 FIX"
    },
    {
        "SL No.": 129,
        "Category": "ROUND RISERS",
        "Base Code": "13806",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 36 FIXED RISER - STEEL - FOR 1.75 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13806 C 36X2.00 FIX"
    },
    {
        "SL No.": 130,
        "Category": "ROUND RISERS",
        "Base Code": "13807",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.0 EXTNS FOR 36\" - CAST IRON - FOR 2.00 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13807 A 36X1.00 CI"
    },
    {
        "SL No.": 131,
        "Category": "ROUND RISERS",
        "Base Code": "13807",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTNS FOR 36\" - CAST IRON - FOR 2.00 THICKNESS COVER(NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13807 B 36X1.50 CI"
    },
    {
        "SL No.": 132,
        "Category": "ROUND RISERS",
        "Base Code": "13807",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.0 EXTNS FOR 36\" - CAST IRON - FOR 2.00 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13807 C 36X2.00 CI"
    },
    {
        "SL No.": 133,
        "Category": "ROUND RISERS",
        "Base Code": "13808",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1.0 X 36 ADJUSTABLE RISER - STEEL- FOR 2.00 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13808 A 36X1.00 ADJ"
    },
    {
        "SL No.": 134,
        "Category": "ROUND RISERS",
        "Base Code": "13808",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 X 36 ADJUSTABLE RISER - STEEL - FOR 2.00 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13808 B 36X1.50 ADJ"
    },
    {
        "SL No.": 135,
        "Category": "ROUND RISERS",
        "Base Code": "13808",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2 X 36 ADJUSTABLE RISER - STEEL - FOR 2.00 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13808 C 36X2.00 ADJ"
    },
    {
        "SL No.": 136,
        "Category": "ROUND RISERS",
        "Base Code": "13809",
        "Suffix": "A",
        "Parsed Size": "36\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.0 X 36 FIXED RISER - STEEL- FOR 2.00 THICKNESS COVER(NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13809 A 36X1.00 FIX"
    },
    {
        "SL No.": 137,
        "Category": "ROUND RISERS",
        "Base Code": "13809",
        "Suffix": "B",
        "Parsed Size": "36\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 X 36 FIXED RISER - STEEL - FOR 2.00 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13809 B 36X1.50 FIX"
    },
    {
        "SL No.": 138,
        "Category": "ROUND RISERS",
        "Base Code": "13809",
        "Suffix": "C",
        "Parsed Size": "36\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2 X 36 FIXED RISER - STEEL - FOR 2.00 THICKNESS COVER (NH-NE)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13809 C 36X2.00 FIX"
    },
    {
        "SL No.": 139,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13904",
        "Suffix": "A",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1\" EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -CAST IRON (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13904 A 24 X 1.00 CI"
    },
    {
        "SL No.": 140,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13904",
        "Suffix": "B",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -CAST IRON (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13904 B 24 X 1.50 CI"
    },
    {
        "SL No.": 141,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13904",
        "Suffix": "C",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2\" EXTN FOR 24X24 - FOR 2\" THICKNESS GRATE -CAST IRON (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13904 C 24 X 2.00 CI"
    },
    {
        "SL No.": 142,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13904",
        "Suffix": "D",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 2.5,
        "Material & Type": "Cast Iron",
        "Description": "2.5\" EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -CAST IRON (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13904 D 24 X 2.50 CI"
    },
    {
        "SL No.": 143,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13905",
        "Suffix": "A",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1\" EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -STEEL ADJUSTABLE (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13905 A 24X1.00 ADJ"
    },
    {
        "SL No.": 144,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13905",
        "Suffix": "B",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -STEEL ADJUSTABLE (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13905 B 24X1.50 ADJ"
    },
    {
        "SL No.": 145,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13905",
        "Suffix": "C",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2\" EXTN FOR 24X24 - FOR 2\" THICKNESS GRATE -STEEL ADJUSTABLE (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13905 C 24X2.00 ADJ"
    },
    {
        "SL No.": 146,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13905",
        "Suffix": "D",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Adjustable",
        "Description": "2.5\" EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13905 D 24X2.50 ADJ"
    },
    {
        "SL No.": 147,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13906",
        "Suffix": "A",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1\" EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13906 A 24X1.00 FIX"
    },
    {
        "SL No.": 148,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13906",
        "Suffix": "B",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -STEEL FIXED(NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13906 B 24X1.50 FIX"
    },
    {
        "SL No.": 149,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13906",
        "Suffix": "C",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2\" EXTN FOR 24X24 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13906 C 24X2.00 FIX"
    },
    {
        "SL No.": 150,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13906",
        "Suffix": "D",
        "Parsed Size": "24\" x 24\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.5\" EXTN FOR 24 X 24 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NEW ENGLAND)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13906 D 24X2.50 FIX"
    },
    {
        "SL No.": 151,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13908",
        "Suffix": "A",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -CAST IRON (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13908 A 23 X 1.00 CI"
    },
    {
        "SL No.": 152,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13908",
        "Suffix": "B",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.5 EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -CAST IRON (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13908 B 23 X 1.50 CI"
    },
    {
        "SL No.": 153,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13908",
        "Suffix": "C",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -CAST IRON (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13908 C 23 X 2.00 CI"
    },
    {
        "SL No.": 154,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13908",
        "Suffix": "D",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 2.5,
        "Material & Type": "Cast Iron",
        "Description": "2.5\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -CAST IRON (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13908 D 23 X 2.50 CI"
    },
    {
        "SL No.": 155,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "A",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 1,
        "Material & Type": "Steel Adjustable",
        "Description": "1\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL ADJUSTABLE (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 A 23X1.00 ADJ"
    },
    {
        "SL No.": 156,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "B",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Adjustable",
        "Description": "1.5 EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL ADJUSTABLE (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 B 23X1.50 ADJ"
    },
    {
        "SL No.": 157,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "C",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 2,
        "Material & Type": "Steel Adjustable",
        "Description": "2\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL ADJUSTABLE (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 C 23X2.00 ADJ"
    },
    {
        "SL No.": 158,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "D",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Adjustable",
        "Description": "2.5\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 D 23X2.50 ADJ"
    },
    {
        "SL No.": 159,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "A",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 A 23X1.00 FIX"
    },
    {
        "SL No.": 160,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "B",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.5 EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL FIXED(NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 B 23X1.50 FIX"
    },
    {
        "SL No.": 161,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "C",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 C 23X2.00 FIX"
    },
    {
        "SL No.": 162,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "D",
        "Parsed Size": "23\" x 21\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.5\" EXTN FOR 23 X 21 - FOR 2\" THICKNESS GRATE -STEEL FIXED (NH)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 D 23X2.50 FIX"
    },
    {
        "SL No.": 163,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "A",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.00\" EXTN FOR B & D INLETS -CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 A B& D 1.00 CI"
    },
    {
        "SL No.": 164,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "B",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.50\" EXTN FOR B & D INLETS -CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 B B&D 1.50 CI"
    },
    {
        "SL No.": 165,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "C",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.00\" EXTN FOR B & D INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 C B&D 2.00 CI"
    },
    {
        "SL No.": 166,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "D",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 2.5,
        "Material & Type": "Cast Iron",
        "Description": "2.50\" FOR B & D INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 D B&D 2.50 CI"
    },
    {
        "SL No.": 167,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13909",
        "Suffix": "E",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 3,
        "Material & Type": "Cast Iron",
        "Description": "3.00\" FOR B & D INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13909 E B&D 3.00 CI"
    },
    {
        "SL No.": 168,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "A",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.00\" EXTN FOR B & D INLETS -STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 A B&D 1.00 STL"
    },
    {
        "SL No.": 169,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "B",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.50\" EXTN FOR B & D INLETS -STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 B B&D 1.50 STL"
    },
    {
        "SL No.": 170,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "C",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2.00\" EXTN FOR B & D INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 C B&D 2.00 STL"
    },
    {
        "SL No.": 171,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "D",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.50\" FOR B & D INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 D B&D 2.50 STL"
    },
    {
        "SL No.": 172,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13910",
        "Suffix": "E",
        "Parsed Size": "B & D Inlets",
        "Height (in)": 3,
        "Material & Type": "Steel Fixed",
        "Description": "3.00\" FOR B & D INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13910 E B&D 3.00 STL"
    },
    {
        "SL No.": 173,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13913",
        "Suffix": "A",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.00\" EXTN FOR E &A INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13913 A E&A 1.00 CI"
    },
    {
        "SL No.": 174,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13913",
        "Suffix": "B",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.50\" EXTN FOR E &A INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13913 B E&A 1.50 CI"
    },
    {
        "SL No.": 175,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13913",
        "Suffix": "C",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.00\" EXTNS FOR E & A INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13913 C E&A 2.00 CI"
    },
    {
        "SL No.": 176,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13913",
        "Suffix": "D",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 2.5,
        "Material & Type": "Cast Iron",
        "Description": "2.50\" EXTN FOR E & A INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13913 D E&A 2.50 CI"
    },
    {
        "SL No.": 177,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13913",
        "Suffix": "E",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 3,
        "Material & Type": "Cast Iron",
        "Description": "3.00\" EXTN FOR E & A INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13913 E E&A 3.00 CI"
    },
    {
        "SL No.": 178,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13914",
        "Suffix": "A",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.00\" EXTN FOR E &A INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13914 A E&A 1.00 STL"
    },
    {
        "SL No.": 179,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13914",
        "Suffix": "B",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.50\" EXTN FOR E &A INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13914 B E&A 1.50 STL"
    },
    {
        "SL No.": 180,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13914",
        "Suffix": "C",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2.00\" EXTNS FOR E & A INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13914 C E&A 2.00 STL"
    },
    {
        "SL No.": 181,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13914",
        "Suffix": "D",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.50\" EXTN FOR E & A INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13914 D E&A 2.50 STL"
    },
    {
        "SL No.": 182,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13914",
        "Suffix": "E",
        "Parsed Size": "E & A Inlets",
        "Height (in)": 3,
        "Material & Type": "Steel Fixed",
        "Description": "3.00\" EXTN FOR E & A INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13914 E E&A 3.00 STL"
    },
    {
        "SL No.": 183,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13917",
        "Suffix": "A",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 1,
        "Material & Type": "Cast Iron",
        "Description": "1.00\" EXTN FOR 30 X 48 FLUSH INLETS -CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13917 A 30X48 1.00 CI"
    },
    {
        "SL No.": 184,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13917",
        "Suffix": "B",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 1.5,
        "Material & Type": "Cast Iron",
        "Description": "1.50\" EXTN FOR 30 X 48 FLUSH INLETS -CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13917 B 30X48 1.50 CI"
    },
    {
        "SL No.": 185,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13917",
        "Suffix": "C",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 2,
        "Material & Type": "Cast Iron",
        "Description": "2.00\" EXTN FOR 30 X 48 FLUSH INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13917 C 30X48 2.00 CI"
    },
    {
        "SL No.": 186,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13917",
        "Suffix": "D",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 2.5,
        "Material & Type": "Cast Iron",
        "Description": "2.50\" FOR 30 X 48 FLUSH INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13917 D 30X48 2.50 CI"
    },
    {
        "SL No.": 187,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13917",
        "Suffix": "E",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 3,
        "Material & Type": "Cast Iron",
        "Description": "3.00\" FOR 30 X 48 FLUSH INLETS - CAST IRON (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13917 E 30X48 3.00 CI"
    },
    {
        "SL No.": 188,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13918",
        "Suffix": "A",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 1,
        "Material & Type": "Steel Fixed",
        "Description": "1.00\" EXTN FOR 30 X 48 FLUSH INLETS -STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13918 A 30X48 1.00 STL"
    },
    {
        "SL No.": 189,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13918",
        "Suffix": "B",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 1.5,
        "Material & Type": "Steel Fixed",
        "Description": "1.50\" EXTN FOR 30 X 48 FLUSH INLETS -STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13918 B 30X48 1.50 STL"
    },
    {
        "SL No.": 190,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13918",
        "Suffix": "C",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 2,
        "Material & Type": "Steel Fixed",
        "Description": "2.00\" EXTN FOR 30 X 48 FLUSH INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13918 C 30X48 2.00 STL"
    },
    {
        "SL No.": 191,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13918",
        "Suffix": "D",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 2.5,
        "Material & Type": "Steel Fixed",
        "Description": "2.50\" FOR 30 X 48 FLUSH INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13918 D 30X48 2.50 STL"
    },
    {
        "SL No.": 192,
        "Category": "SQUARE & RECTANGULAR RISERS",
        "Base Code": "13918",
        "Suffix": "E",
        "Parsed Size": "30\" x 48\"",
        "Height (in)": 3,
        "Material & Type": "Steel Fixed",
        "Description": "3.00\" FOR 30 X 48 FLUSH INLETS - STEEL FIXED (NJ & NYS)",
        "Weight (lbs)": null,
        "Trenching NO. (Raw)": "13918 E 30X48 3.00 STL"
    }
];
